# Generated by Django 4.0.4 on 2022-05-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('attraction', 'Attraction'), ('culture', 'Culture'), ('natural parks and reserves', 'Natural Parks And Reserves'), ('animals', 'Animals'), ('plants', 'Plants'), ('sport', 'Sport'), ('health', 'Health'), ('extreme', 'Extreme')], default='world', max_length=50),
        ),
    ]
