# Generated by Django 4.0.4 on 2022-05-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_day_remove_blogpost_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='day',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='month',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
