# Generated by Django 4.0.4 on 2022-06-09 03:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('other', 'Other'), ('caravanning', 'Caravanning'), ('banana', 'Banana'), ('rope_park', 'Fope Park'), ('bike_ride', 'Bike Ride'), ('horse_ride', 'Horse Ride'), ('camping', 'Camping'), ('liner', 'Liner'), ('skis', 'Skis'), ('hunting', 'Hunting'), ('para', 'Para'), ('fishing', 'Fishing'), ('snow_scooter', 'Snow Scooter'), ('alloy', 'Alloy'), ('photo_tourism', 'Photo Tourism'), ('ecotourism', 'Ecotourism')], default='other', max_length=50)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
